//action cua saga
export const LOADING_GET_CURRENT_WEATHER = 'LOADING_GET_CURRENT_WEATHER';
export const GET_CURRENT_WEATHER_SUCCESS = 'GET_CURRENT_WEATHER_SUCCESS';
export const GET_CURRENT_WEATHER_FAILED = 'GET_CURRENT_WEATHER_FAILED';

// action cua user
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';
